variable "image_owners" {}
variable "image_name" {}
variable "root_device_type" {}
variable "architecture_type" {}
variable "public_key_name" {}
variable "public_subnet_ids" {}
variable "instance_type" {}
variable "def_route" {}
variable "vpc_id" {}
