variable "project_name" {}
variable "profile_name" {}
variable "vpc_cidr" {}
variable "region" {}
variable "availability_zone" {}
variable "private_subnet_cidr" {}
variable "public_subnet_cidr" {}
variable "DB_subnet_cidr" {}
variable "def_route" {}
variable "eip_domain" {}
variable "public_key_path" {}
variable "public_key_name" {}
variable "lb_type" {}
variable "health_check_path" {}
variable "tg_port" {}
variable "tg_protocol" {}
variable "tg_listener_default_action_type" {}
variable "image_owners" {}
variable "architecture_type" {}
variable "virtualization_type" {}
variable "root_device_type" {}
variable "image_name" {}
variable "launch_template_name_prefix" {}
variable "launch_template_instance_type" {}
variable "autoscaling_desired_capacity" {}
variable "autoscaling_max_size" {}
variable "autoscaling_min_size" {}
variable "launch_template_image_1" {}
variable "launch_template_image_2" {}
variable "value_for_on_demand_base_capacity" {}
variable "value_for_on_demand_percentage_above_base_capacity" {}
variable "value_of_spot_allocation_strategy" {}
variable "weighted_capacity_1" {}
variable "weighted_capacity_2" {}