variable "image_owners" {}
variable "architecture_type" {}
variable "virtualization_type" {}
variable "root_device_type" {}
variable "image_name" {}
variable "launch_template_name_prefix" {}
variable "launch_template_instance_type" {}
variable "autoscaling_desired_capacity" {}
variable "autoscaling_max_size" {}
variable "autoscaling_min_size" {}
variable "private_subnet_ids" {}
variable "public_key_name" {}
variable "elb_SG_id" {}
variable "launch_template_image_1" {}
variable "launch_template_image_2" {}
variable "value_for_on_demand_base_capacity" {}
variable "value_for_on_demand_percentage_above_base_capacity" {}
variable "value_of_spot_allocation_strategy" {}
variable "weighted_capacity_1" {}
variable "weighted_capacity_2" {}
variable "target_group_arn" {}